### ISSUE TITLE
Is AWS KMS supported or plans to support?

### ISSUE THREAD

**Issue by Nr18** [elastic/elasticsearch-cloud-aws#282] opened 2016-12-09 13:46 UTC
I have set server_side_encryption to true and i now i have AES256 encryption but i would like to use my own key using KMS, is this supported or are there plans to support this in the future?

**Comment by dadoonet** [comment] 2016-12-09 14:14
It's a duplicate of https://github.com/elastic/elasticsearch/issues/18561 which is waiting for a dev :)

**Closed as completed by dadoonet** 2016-12-09 14:14 UTC
